
language: java
jdk:
  - openjdk14

sudo: false

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432
   # - CODECOV_TOKEN="dca401a0-aa7c-4758-8259-9c2e5dbea0e0"
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
before_install:
  - psql -c 'create database tracker;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -lextor78@gmail.com
    on_success: change # default: change
    on_failure: always # default: always